name: Github Issue to Shortcut Story
on: 
  issues:
    types: [labeled, unlabeled]
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Use issue github action
      uses: hunhoon21/github-issue-to-shortcut-story@v0.0.9
      with:
        shortcut_api_token: ${{ secrets.SHORTCUT_API_TOKEN }}
        label_to_create_shortcut_story: "shortcut"
        github_token: ${{ secrets.TOKEN }}
