name: Github Issue to Shortcut Story
on: 
  issues:
<<<<<<< HEAD
    types: [labeled, unlabeled]
=======
    types: [opened]
>>>>>>> 33ded3ae8aa29f348d5fe48ddf824920882e0760
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Print environment variables
      run: |
        printenv
<<<<<<< HEAD
      with:
        shortcut_api_token: ${{ secrets.SHORTCUT_API_TOKEN}}
=======
>>>>>>> 33ded3ae8aa29f348d5fe48ddf824920882e0760
