name: Update Release
on:
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - released
jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    # - name: Test
    #   run: echo "HELLO"
    # - name: Test scripts
    #   run: python scripts/upload-release.py
    # - name: env Test
    #   run: env
